// Frontend/react/webapp/src/DetailsPanel.jsx
import React, { useState } from "react";
import PhotoGallery from "./PhotoGallery";

export default function DetailsPanel({ point }) {
  const [showPhotos, setShowPhotos] = useState(false);
  
  if (!point) {
    return (
      <div style={{padding: 24, color: '#888', textAlign: 'center'}}>
        <div style={{fontSize: '48px', marginBottom: '12px'}}>📍</div>
        <p>Sélectionnez un point sur la carte pour voir les détails.</p>
      </div>
    );
  }
  
  const getStatusColor = (status) => {
    switch(status?.toLowerCase()) {
      case 'termine': case 'terminé': return '#4caf50';
      case 'en cours': return '#ffc107';
      case 'nouveau': return '#2196f3';
      default: return '#9e9e9e';
    }
  };
  
  return (
    <>
      <div style={{padding: 24, minWidth: 320, maxWidth: 400, background: '#fafaff', borderLeft: '1px solid #eee', height: '100%', overflow: 'auto'}}>
        <h3 style={{marginBottom: 16, color: '#2c3e50', fontSize: '20px'}}>{point.titre || 'Travaux routier'}</h3>
        <ul style={{listStyle: 'none', padding: 0, fontSize: 15, lineHeight: '2'}}>
          <li style={{padding: '8px 0', borderBottom: '1px solid #f0f0f0'}}>
            <span style={{color: '#666'}}>Status :</span>{' '}
            <span style={{
              color: getStatusColor(point.status), 
              fontWeight: 'bold',
              padding: '4px 12px',
              borderRadius: '12px',
              background: getStatusColor(point.status) + '20'
            }}>
              {point.status}
            </span>
          </li>
          <li style={{padding: '8px 0', borderBottom: '1px solid #f0f0f0'}}>
            <span style={{color: '#666'}}>Date :</span> <b>{point.date || '-'}</b>
          </li>
          <li style={{padding: '8px 0', borderBottom: '1px solid #f0f0f0'}}>
            <span style={{color: '#666'}}>Surface :</span> <b>{point.surface || '-'} m²</b>
          </li>
          <li style={{padding: '8px 0', borderBottom: '1px solid #f0f0f0'}}>
            <span style={{color: '#666'}}>Budget :</span> <b>{point.budget ? `${point.budget.toLocaleString()} Ar` : '-'}</b>
          </li>
          <li style={{padding: '8px 0', borderBottom: '1px solid #f0f0f0'}}>
            <span style={{color: '#666'}}>Entreprise :</span> <b>{point.entreprise || '-'}</b>
          </li>
          <li style={{padding: '8px 0', borderBottom: '1px solid #f0f0f0'}}>
            <span style={{color: '#666'}}>Coordonnées :</span> <span style={{fontSize: '13px', color: '#888'}}>[{point.latitude.toFixed(4)}, {point.longitude.toFixed(4)}]</span>
          </li>
        </ul>
        
        <div style={{marginTop: '24px', paddingTop: '16px', borderTop: '2px solid #eee'}}>
          <button
            onClick={() => setShowPhotos(true)}
            style={{
              width: '100%',
              padding: '12px',
              background: '#2196f3',
              color: 'white',
              border: 'none',
              borderRadius: '6px',
              fontSize: '15px',
              fontWeight: '600',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '8px'
            }}
          >
            📷 Voir les photos
          </button>
        </div>
      </div>

      {/* Modal de la galerie de photos */}
      {showPhotos && (
        <div
          onClick={() => setShowPhotos(false)}
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background: 'rgba(0, 0, 0, 0.7)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1000
          }}
        >
          <div
            onClick={(e) => e.stopPropagation()}
            style={{
              background: 'white',
              borderRadius: '12px',
              maxWidth: '900px',
              width: '90%',
              maxHeight: '90vh',
              overflow: 'auto',
              position: 'relative'
            }}
          >
            <button
              onClick={() => setShowPhotos(false)}
              style={{
                position: 'absolute',
                top: '16px',
                right: '16px',
                background: '#ff6b6b',
                color: 'white',
                border: 'none',
                borderRadius: '50%',
                width: '36px',
                height: '36px',
                fontSize: '20px',
                cursor: 'pointer',
                zIndex: 10
              }}
            >
              ✕
            </button>
            <PhotoGallery signalementId={point.id} canEdit={false} />
          </div>
        </div>
      )}
    </>
  );
}

// Frontend/mobile-vue-app/src/components/DetailsPanel.vue
<template>
  <div class="details-panel">
    <h3>Détails du point</h3>
    <div v-if="!point" class="no-selection">
      <p>Cliquez sur un point sur la carte pour voir les détails</p>
    </div>
    <div v-else class="point-details">
      <div class="detail-header">
        <h4>{{ point.titre || 'Travaux routier' }}</h4>
        <span :class="getStatusClass(point.status)">{{ point.status }}</span>
      </div>
      <div class="detail-grid">
        <div class="detail-item">
          <label>Date :</label>

          
          <span>{{ point.date || '-' }}</span>
        </div>
        <div class="detail-item">
          <label>Latitude :</label>
          <span>{{ point.latitude.toFixed(6) }}</span>
        </div>
        <div class="detail-item">
          <label>Longitude :</label>
          <span>{{ point.longitude.toFixed(6) }}</span>
        </div>
        <div class="detail-item">
          <label>Surface :</label>
          <span>{{ point.surface || '-' }} m²</span>
        </div>
        <div class="detail-item">
          <label>Budget :</label>
          <span>{{ point.budget || '-' }} Ar</span>
        </div>
        <div class="detail-item">
          <label>Entreprise :</label>
          <span>{{ point.entreprise || '-' }}</span>
        </div>
      </div>

      <div class="actions">
        <button @click="viewOnMap" class="btn-primary">
          📍 Voir sur la carte
        </button>
        <button @click="shareLocation" class="btn-secondary">
          📤 Partager la position
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { defineProps } from 'vue';

const props = defineProps({
  point: {
    type: Object,
    default: null
  }
});

const getStatusClass = (status) => {
  switch(status) {
    case 'termine': return 'status-termine';
    case 'en cours': return 'status-en-cours';
    case 'nouveau': return 'status-nouveau';
    default: return 'status-default';
  }
};

const viewOnMap = () => {
  if (props.point) {
    // This would center the map on the selected point
    // Implementation depends on how the map component is structured
    console.log('View on map:', props.point);
  }
};

const shareLocation = () => {
  if (props.point && navigator.share) {
    navigator.share({
      title: props.point.titre || 'Point de travaux',
      text: `Position: ${props.point.latitude}, ${props.point.longitude}`,
      url: `https://www.openstreetmap.org/?mlat=${props.point.latitude}&mlon=${props.point.longitude}&zoom=15`
    });
  } else {
    // Fallback: copy to clipboard
    const text = `Position: ${props.point.latitude}, ${props.point.longitude}`;
    navigator.clipboard.writeText(text).then(() => {
      alert('Position copiée dans le presse-papiers');
    });
  }
};
</script>

<style scoped>
.details-panel {
  background: white;
  border-radius: 12px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  padding: 20px;
  height: fit-content;
}

.details-panel h3 {
  margin-bottom: 20px;
  color: #2c3e50;
  text-align: center;
}

.no-selection {
  text-align: center;
  color: #7f8c8d;
  padding: 40px 20px;
}

.point-details {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.detail-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-bottom: 15px;
  border-bottom: 2px solid #ecf0f1;
}

.detail-header h4 {
  margin: 0;
  color: #2c3e50;
  font-size: 1.2rem;
}

.detail-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 15px;
}

.detail-item {
  display: flex;
  flex-direction: column;
  gap: 5px;
}

.detail-item label {
  font-weight: 600;
  color: #34495e;
  font-size: 0.9rem;
}

.detail-item span {
  color: #2c3e50;
  font-size: 0.95rem;
}

.actions {
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding-top: 20px;
  border-top: 1px solid #ecf0f1;
}

.btn-primary, .btn-secondary {
  padding: 12px 16px;
  border: none;
  border-radius: 6px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s ease;
}

.btn-primary {
  background: #3498db;
  color: white;
}

.btn-primary:hover {
  background: #2980b9;
}

.btn-secondary {
  background: #ecf0f1;
  color: #2c3e50;
}

.btn-secondary:hover {
  background: #d5dbdb;
}

.status-termine {
  color: #27ae60;
  font-weight: bold;
  background: #d5f4e6;
  padding: 4px 8px;
  border-radius: 4px;
  font-size: 0.85rem;
}

.status-en-cours {
  color: #f39c12;
  font-weight: bold;
  background: #fdeaa7;
  padding: 4px 8px;
  border-radius: 4px;
  font-size: 0.85rem;
}

.status-nouveau {
  color: #3498db;
  font-weight: bold;
  background: #d6eaf8;
  padding: 4px 8px;
  border-radius: 4px;
  font-size: 0.85rem;
}

.status-default {
  color: #95a5a6;
  font-weight: bold;
  background: #ecf0f1;
  padding: 4px 8px;
  border-radius: 4px;
  font-size: 0.85rem;
}

@media (max-width: 768px) {
  .detail-grid {
    grid-template-columns: 1fr;
  }

  .detail-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 10px;
  }

  .actions {
    flex-direction: column;
  }
}
</style>
